apiVersion: v1
kind: Secret
metadata:
  name: task-secret
type: Opaque
data:
  java-thread: MTA= # This is the base64 encoded value for "redis-host"
  virtual-thread: MTA=       # This is the base64 encoded value for "6379"