name: Docker Image CI

on:
  push:
    branches: [ "demo_j21_graal_native_docker" ]
  pull_request:
    branches: [ "demo_j21_graal_native_docker" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Install sdk man
      run: curl -s "https://get.sdkman.io" | bash

    - name: Activate sdk
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh"

    - name: Check sdk
      run:  source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk version

    - name: Install java
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk install java 21-graalce 

    - name: Setting java
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk default java 21-graalce

    - name: Check java
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        java -version

    - name: Install gradle
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk install gradle 8.3

    - name: Check gradle
      run: gradle --version

    - name: Build Native
      run: |
        ls
        gradle nativeCompile
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag demoj21:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: leosaviobh/demoj21:latest
