name: Docker Image CI

on:
  push:
    branches: [ "demo_j21_graal_native_docker" ]
    paths-ignore:
      - '_*/**'
  pull_request:
    branches: [ "demo_j21_graal_native_docker" ]
    paths-ignore:
      - '_*/**'

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v3
    - name: Install sdk man
      run: curl -s "https://get.sdkman.io" | bash

    - name: Activate sdk
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh"

    - name: Check sdk
      run:  source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk version

    - name: Install java
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk install java 21-graalce 

    - name: Setting java
      run: source "/home/runner/.sdkman/bin/sdkman-init.sh" && sdk default java 21-graalce

    - name: Check java
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        java -version

    - name: Build Native
      run: |
        ls
        chmod +x gradlew
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        ./gradlew clean nativeCompile

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: leosaviobh/demoj21:latest
